name: CI
on:
  - push
  - pull_request

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v9.0.0
        with:
          enable-cache: true
      - run: uv sync --all-extras
      - run: uv run ruff format --check

  marimo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v9.0.0
        with:
          enable-cache: true
      - run: uv sync --all-extras
      - uses: extractions/setup-just@v4
      - run: just example-test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v9.0.0
        with:
          enable-cache: true
      - uses: extractions/setup-just@v4
      - run: just lint

  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v9.0.0
        with:
          enable-cache: true
      - uses: extractions/setup-just@v4
      - run: just doc

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v9.0.0
        with:
          enable-cache: false
          python-version: ${{ matrix.python-version }}
      - uses: extractions/setup-just@v4
      - run: just test

  publish:
    runs-on: ubuntu-latest
    if: startsWith(github.event.ref, 'refs/tags/v')
    needs: [format, lint, test, doc]
    environment:
      name: pypi
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v9.0.0
      - run: uv python install 3.12
      - run: uv build
      - run: uv publish
